//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHubFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int ReceiptsID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ShowID { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
        public string MovieName { get; set; }
        public string Seats { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Shows Shows { get; set; }
    }
}
