//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaHubFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shows()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int ShowID { get; set; }
        public string MovieName { get; set; }
        public Nullable<System.DateTime> ShowTime { get; set; }
        public bool Seat0 { get; set; }
        public bool Seat1 { get; set; }
        public bool Seat2 { get; set; }
        public bool Seat3 { get; set; }
        public bool Seat4 { get; set; }
        public bool Seat5 { get; set; }
        public bool Seat6 { get; set; }
        public bool Seat7 { get; set; }
        public bool Seat8 { get; set; }
        public bool Seat9 { get; set; }
        public bool Seat10 { get; set; }
        public bool Seat11 { get; set; }
        public bool Seat12 { get; set; }
        public bool Seat13 { get; set; }
        public bool Seat14 { get; set; }
        public bool Seat15 { get; set; }
        public bool Seat16 { get; set; }
        public bool Seat17 { get; set; }
        public bool Seat18 { get; set; }
        public bool Seat19 { get; set; }
        public bool Seat20 { get; set; }
        public bool Seat21 { get; set; }
        public bool Seat22 { get; set; }
        public bool Seat23 { get; set; }
        public bool Seat24 { get; set; }
        public bool Seat25 { get; set; }
    
        public virtual Movies Movies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
